<?php

return array (
  'specList.model' => 'static',
  'specList.cuttingSymbol' => ',',
  'specList.dataEmptyText' => NULL,
  'specList.static.search.status' => false,
  'specList.static.search.default' => '1',
  'specList.static.search.caseSensitive' => false,
  'specList.static.search.class' => NULL,
  'specList.static.search.inputConfig.onInput' => true,
  'specList.static.search.inputConfig.onChange' => true,
  'specList.static.search.inputConfig.class' => NULL,
  'specList.static.search.inputConfig.componentConfig' => 'maxlength:10|placeholder:input search|clearable:true',
  'specList.static.search.buttonConfig.status' => false,
  'specList.static.search.buttonConfig.text' => NULL,
  'specList.static.search.buttonConfig.class' => NULL,
  'specList.static.search.buttonConfig.componentConfig' => NULL,
  'specList.static.screen.status' => true,
  'specList.static.screen.userStatus' => false,
  'specList.static.screen.clearText' => 'clear',
  'specList.static.screen.selectedClass' => NULL,
  'specList.static.screen.countStatus' => true,
  'specList.static.screen.groupCountType' => 
  array (
    0 => '1',
    1 => '2',
  ),
  'specList.static.screen.type' => '1',
  'specList.static.screen.nullHidden' => false,
  'specList.static.screen.class' => NULL,
  'specList.static.screen.allClass' => NULL,
  'specList.static.selector.class' => NULL,
  'specList.static.selector.list.table.text' => NULL,
  'specList.static.selector.list.list.text' => NULL,
  'specList.static.selector.config.componentConfig' => NULL,
  'specList.static.pagination.class' => NULL,
  'specList.static.pagination.pageSize' => NULL,
  'specList.static.pagination.currentPage' => NULL,
  'specList.static.pagination.componentConfig' => 'layout:total, sizes, prev, pager, next, jumper',
  'specList.static.loading.status' => true,
  'specList.static.loading.config.componentConfig' => 'text:loading...',
);
